### PR TITLE
Se23

### PR DESCRIPTION
**Pull request by JohannLac**
1- Add SE23 and time machines groups
2- Fix a bug in SO3 where the jacobian/inv jacobian for a null rotation was wrongly set to zero instead of identity

### CODE REVIEW

**Review by keenan-burnett — APPROVED** [review]

**Comment by keenan-burnett** [comment]
Looks good to me! :sunglasses:

**Comment by keenan-burnett** [comment]
Could you try squashing your commits into 1 single commit before merging?

**Comment by JohannLac** [comment]
Done, let me know if there's anything else!

**Comment by keenan-burnett** [comment]
Looks good to merge

**Pull request merged**
